# Use an official Python runtime as a parent image
FROM python:3.9-slim

# Set the working directory to /app
WORKDIR /application

# Copy the requirements file into the container and install dependencies
COPY requirements_fastapi.txt ./
RUN pip install --no-cache-dir -r requirements_fastapi.txt

# Copy the FastAPI file into the container
COPY fastapi_hello.py .

# Expose the port that the app will be running on
EXPOSE 8000

# Start the app
CMD ["uvicorn", "fastapi_hello:testapp", "--host", "0.0.0.0", "--port", "8000"]
