# Use an official Python runtime as a parent image
FROM python:3.9-slim

# Set the working directory to /app
WORKDIR /application

# Copy the requirements file into the container and install dependencies
COPY requirements_flask.txt ./
RUN pip install --no-cache-dir -r requirements_flask.txt

# Copy the FastAPI file into the container
COPY flask_hello.py .

# Expose the port that the app will be running on
EXPOSE 5000

# Start the app
CMD ["python", "flask_hello.py"]
